version: "3.5"

services:
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - discounts
    command: host.docker.internal:5000

  discounts: 
    build: ./
    ports:
     - '5000:5000'
    environment:
      - rabbitMq:username:=guest 
      - rabbitMq:password:=guest 
      - rabbitMq:port:=5672 
      - rabbitMq:virtualHost:=/ 
      - rabbitMq:hostnames:0=rabbitmq_test
      - mongo:connectionString=mongodb://mongodb_test:27017
      - mongo:database=discounts_db_test
    networks:
      - dshop

  tests:
    build: 
      context: ./
      dockerfile: Dockerfile.integration
    depends_on:
      - discounts
    networks:
      - dshop 

networks:
  dshop:
    name: dshop-network


